# CUDA 11.8 이미지를 기반으로 함
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

# 필수 패키지 업데이트 및 설치
RUN apt-get update && apt-get install -y \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 아나콘다 설치
RUN wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh -O ~/anaconda.sh \
    && bash ~/anaconda.sh -b -p /opt/conda \
    && rm ~/anaconda.sh

# 아나콘다를 환경 변수에 추가
ENV PATH="/opt/conda/bin:${PATH}"

# 기본 환경에서 Python 3.11 설치
RUN conda install -y python=3.11

# 작업 디렉토리 생성
WORKDIR /app

# requirements.txt 복사
COPY requirements.txt .

# 기본 환경에서 requirements.txt 설치
RUN /opt/conda/bin/pip install -r requirements.txt
RUN /opt/conda/bin/pip install opencv-python-headless

RUN /opt/conda/bin/pip install -U "jax[cuda12]"
RUN apt-get update && apt-get install -y cuda-compat-12-2

# 컨테이너 실행 시 기본 Python 명령어 설정
CMD ["bash"]